# Generated by Django 3.0.6 on 2020-05-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenticeshipdevelop',
            name='url',
            field=models.URLField(default='#', max_length=400),
        ),
    ]
