# Generated by Django 2.1.15 on 2020-05-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
