version: '3'

services:
  web:
    build: .
    volumes:
      # mount local to container so changes are reflected.
      - .:/app

        # for development only, use runserver - production will use gunicorn
    command: ./manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env.dev

  db:
    image:  postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
    postgres_data: